### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [rburgst/time-tracker-mac#147]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [1.3.13 release files](https://code.google.com/p/time-tracker-mac/downloads/list) to somewhere else? (eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by rburgst** [comment]
they are already there: https://github.com/rburgst/time-tracker-mac/releases

**Comment by rburgst** [comment]
they are already on github: https://github.com/rburgst/time-tracker-mac/releases

**Comment by tsparber** [comment]
These are source only releases. I would be interested in binary releases. You could edit the existing releases on GitHub and add (Drag'n'Drop) the build zip from Google Code.

**Comment by rburgst** [comment]
done, had to create a new release though.
https://github.com/rburgst/time-tracker-mac/releases/latest

**Comment by tsparber** [comment]
Thank you!
